"""add_facemap_shares_table

Revision ID: 208caaa13f06
Revises: a7ed7634de1e
Create Date: 2026-03-02 14:00:38.295509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '208caaa13f06'
down_revision: Union[str, Sequence[str], None] = 'a7ed7634de1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facemap_shares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('image_file_id', sa.String(length=32), nullable=False),
    sa.Column('share_type', sa.String(length=20), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('locale', sa.String(length=10), server_default='zh-CN', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facemap_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facemap_shares_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_facemap_shares_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_facemap_shares_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_facemap_shares_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facemap_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facemap_shares_user_id'))
        batch_op.drop_index(batch_op.f('ix_facemap_shares_token'))
        batch_op.drop_index(batch_op.f('ix_facemap_shares_expires_at'))
        batch_op.drop_index(batch_op.f('ix_facemap_shares_content_hash'))

    op.drop_table('facemap_shares')
    # ### end Alembic commands ###
