"""add_failed_code_attempts_to_file_transfers

Revision ID: 6b28c5c5772b
Revises: 9c4a64e63407
Create Date: 2026-02-28 02:04:16.887026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b28c5c5772b'
down_revision: Union[str, Sequence[str], None] = '9c4a64e63407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_code_attempts', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_transfers', schema=None) as batch_op:
        batch_op.drop_column('failed_code_attempts')

    # ### end Alembic commands ###
