"""add_file_transfer_tables

Revision ID: 9c4a64e63407
Revises: 22a1a3ae1076
Create Date: 2026-02-28 01:42:43.657051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c4a64e63407'
down_revision: Union[str, Sequence[str], None] = '22a1a3ae1076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_transfers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('extract_code', sa.String(length=4), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_downloads', sa.Integer(), nullable=True),
    sa.Column('download_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('total_size', sa.Integer(), server_default='0', nullable=False),
    sa.Column('file_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_transfers_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_transfers_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_file_transfers_user_id'), ['user_id'], unique=False)

    op.create_table('transfer_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['transfer_id'], ['file_transfers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfer_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfer_files_transfer_id'), ['transfer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfer_files_transfer_id'))

    op.drop_table('transfer_files')
    with op.batch_alter_table('file_transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_transfers_user_id'))
        batch_op.drop_index(batch_op.f('ix_file_transfers_token'))
        batch_op.drop_index(batch_op.f('ix_file_transfers_expires_at'))

    op.drop_table('file_transfers')
    # ### end Alembic commands ###
