"""add_burn_after_read_to_file_transfers

Revision ID: a7ed7634de1e
Revises: 6b28c5c5772b
Create Date: 2026-02-28 02:20:45.571665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ed7634de1e'
down_revision: Union[str, Sequence[str], None] = '6b28c5c5772b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('burn_after_read', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_transfers', schema=None) as batch_op:
        batch_op.drop_column('burn_after_read')

    # ### end Alembic commands ###
