"""add_tools_table

Revision ID: e02ee35ad0f7
Revises: 208caaa13f06
Create Date: 2026-03-03 10:45:46.449843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e02ee35ad0f7'
down_revision: Union[str, Sequence[str], None] = '208caaa13f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tools',
    sa.Column('tool_name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('credit_cost', sa.Integer(), nullable=False),
    sa.Column('display_name_zh', sa.String(length=100), nullable=True),
    sa.Column('display_name_en', sa.String(length=100), nullable=True),
    sa.Column('description_zh', sa.String(length=500), nullable=True),
    sa.Column('description_en', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('access_level', sa.String(length=20), nullable=False),
    sa.Column('daily_limit_anon', sa.Integer(), nullable=True),
    sa.Column('daily_limit_auth', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('tool_name')
    )

    # Seed default tool configurations
    tools_table = sa.table(
        'tools',
        sa.column('tool_name', sa.String),
        sa.column('category', sa.String),
        sa.column('display_order', sa.Integer),
        sa.column('is_enabled', sa.Boolean),
        sa.column('credit_cost', sa.Integer),
        sa.column('access_level', sa.String),
    )
    op.bulk_insert(tools_table, [
        # Image tools
        {"tool_name": "image/compress",      "category": "image",   "display_order": 1,  "is_enabled": True, "credit_cost": 0, "access_level": "public"},
        {"tool_name": "image/heic-to-jpg",   "category": "image",   "display_order": 2,  "is_enabled": True, "credit_cost": 0, "access_level": "public"},
        {"tool_name": "image/convert",       "category": "image",   "display_order": 3,  "is_enabled": True, "credit_cost": 0, "access_level": "public"},
        {"tool_name": "image/remove-bg",     "category": "image",   "display_order": 4,  "is_enabled": True, "credit_cost": 0, "access_level": "public"},
        {"tool_name": "image/upscale",       "category": "image",   "display_order": 5,  "is_enabled": True, "credit_cost": 0, "access_level": "public"},
        {"tool_name": "image/restore-face",  "category": "image",   "display_order": 6,  "is_enabled": True, "credit_cost": 0, "access_level": "public"},
        {"tool_name": "image/denoise",       "category": "image",   "display_order": 7,  "is_enabled": True, "credit_cost": 0, "access_level": "public"},
        {"tool_name": "image/colorize",      "category": "image",   "display_order": 8,  "is_enabled": True, "credit_cost": 0, "access_level": "public"},
        {"tool_name": "image/inpaint",       "category": "image",   "display_order": 9,  "is_enabled": True, "credit_cost": 0, "access_level": "public"},
        {"tool_name": "image/ocr",           "category": "image",   "display_order": 10, "is_enabled": True, "credit_cost": 0, "access_level": "public"},
        {"tool_name": "image/segment",       "category": "image",   "display_order": 11, "is_enabled": True, "credit_cost": 0, "access_level": "public"},
        {"tool_name": "image/mosaic",        "category": "image",   "display_order": 12, "is_enabled": True, "credit_cost": 0, "access_level": "public"},
        {"tool_name": "image/scan-enhance",  "category": "image",   "display_order": 13, "is_enabled": True, "credit_cost": 0, "access_level": "public"},
        # PDF tools
        {"tool_name": "pdf/compress",        "category": "pdf",     "display_order": 14, "is_enabled": True, "credit_cost": 0, "access_level": "public"},
        {"tool_name": "pdf/merge",           "category": "pdf",     "display_order": 15, "is_enabled": True, "credit_cost": 0, "access_level": "public"},
        {"tool_name": "pdf/pages",           "category": "pdf",     "display_order": 16, "is_enabled": True, "credit_cost": 0, "access_level": "public"},
        {"tool_name": "pdf/split",           "category": "pdf",     "display_order": 17, "is_enabled": True, "credit_cost": 0, "access_level": "public"},
        {"tool_name": "pdf/from-images",     "category": "pdf",     "display_order": 18, "is_enabled": True, "credit_cost": 0, "access_level": "public"},
        # FaceMap tools
        {"tool_name": "facemap/profile",     "category": "facemap", "display_order": 19, "is_enabled": True, "credit_cost": 0, "access_level": "public"},
        {"tool_name": "facemap/report",      "category": "facemap", "display_order": 20, "is_enabled": True, "credit_cost": 1, "access_level": "verified"},
        {"tool_name": "facemap/similarity",  "category": "facemap", "display_order": 21, "is_enabled": True, "credit_cost": 0, "access_level": "public"},
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tools')
    # ### end Alembic commands ###
